### ISSUE TITLE
Getting user input using 'require('sketch/ui')'

### ISSUE THREAD

**Issue by johnsonzsong** [julianburr/sketch-plugin-boilerplate#8]
Hey @julianburr , I'm having trouble using the provided Sketch API reference to get a user input within sketch. I want to do something like this:

```
var UI = require('sketch/ui');
const response = UI.getStringFromUser("Enter a string", 'e.g. hello');
```

but when I run yarn build on the boilerplate, I get this error on build:

> ModuleNotFoundError: Module not found: Error: Can't resolve 'sketch/ui'

Any suggestions would be much appreciated!!

**Comment by julianburr** [comment]
The problem is that webpack interprets the require as an import and tries to fetch `sketch/ui` from npm. Will need to look into how we can expose to global require from Sketch.

**Comment by johnsonzsong** [comment]
@julianburr Thank you! So what is a workaround to get User Input?

**Comment by julianburr** [comment]
Hey @johnsonzsong, sorry that I took so long with the answer, I didn't forget about you, I'm just pretty busy atm 😞 

I added a plugin to the webpack config that makes webpack ignore any requires of `sketch` or `sketch/*`, which should solve the problem.

Can you check the latest master if everything works now for you?

Also I generally encourage everyone to have a look at https://skpm.io/, since its actively maintained by the guy who develops the Sketch JS API :smile::+1:

**Comment by johnsonzsong** [comment]
@julianburr No worries!! You've been so helpful already, thank you so much for answering my questions. I will pull the updated master and let you know how it goes!
